import "./globals.css";
import { Quicksand } from "next/font/google";

const quicksand = Quicksand({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Goshen City School",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${quicksand.className}  max-w-screen`}>{children}</body>
    </html>
  );
}
